/*
 * instruction_tbl.c
 *
 *  Created on: Jun 8, 2020
 *      Author: David Jonsson
 */

#include "instruction_tbl.h"

struct instruction instruction_tbl[256] =
{
        [0x69] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = adc, .set_operand = immediate,           .flags_ = 0 },
        [0x65] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = adc, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0x75] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = adc, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0x6d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = adc, .set_operand = absolute,            .flags_ = READ_DATA },
        [0x7d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = adc, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x79] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = adc, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x61] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = adc, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0x71] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = adc, .set_operand = indirect_indexed,    .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x29] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = and, .set_operand = immediate,           .flags_ = 0 },
        [0x25] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = and, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0x35] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = and, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0x2d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = and, .set_operand = absolute,            .flags_ = READ_DATA },
        [0x3d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = and, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x39] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = and, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x21] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = and, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0x31] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = and, .set_operand = indirect_indexed,    .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x0a] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = asl, .set_operand = accumulator,         .flags_ = 0 },
        [0x06] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = asl, .set_operand = zero_page,           .flags_ = READ_DATA | WRITE_DATA },
        [0x16] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = asl, .set_operand = zero_page_x,         .flags_ = READ_DATA | WRITE_DATA },
        [0x0e] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = asl, .set_operand = absolute,            .flags_ = READ_DATA | WRITE_DATA },
        [0x1e] = { .nr_bytes_ = 3, .nr_cycles_ = 7, .execute = asl, .set_operand = absolute_x,          .flags_ = READ_DATA | WRITE_DATA },
        [0x90] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bcc, .set_operand = relative,            .flags_ = BRANCH_FLAG },
        [0xb0] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bcs, .set_operand = relative,            .flags_ = BRANCH_FLAG },
        [0xf0] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = beq, .set_operand = relative,            .flags_ = BRANCH_FLAG },
        [0x24] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = bit, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0x2c] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = bit, .set_operand = absolute,            .flags_ = READ_DATA },
        [0x30] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bmi, .set_operand = relative,            .flags_ = 0 },
        [0xd0] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bne, .set_operand = relative,            .flags_ = 0 },
        [0x10] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bpl, .set_operand = relative,            .flags_ = 0 },
        [0x00] = { .nr_bytes_ = 2, .nr_cycles_ = 7, .execute = brk, .set_operand = implied,             .flags_ = 0 },
        [0x50] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bvc, .set_operand = relative,            .flags_ = 0 },
        [0x70] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = bvs, .set_operand = relative,            .flags_ = 0 },
        [0x18] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = clc, .set_operand = implied,             .flags_ = 0 },
        [0xd8] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = cld, .set_operand = implied,             .flags_ = 0 },
        [0x58] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = cli, .set_operand = implied,             .flags_ = 0 },
        [0xb8] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = clv, .set_operand = implied,             .flags_ = 0 },
        [0xc9] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = cmp, .set_operand = immediate,           .flags_ = 0 },
        [0xc5] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = cmp, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xd5] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = cmp, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0xcd] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = cmp, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xdd] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = cmp, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xd9] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = cmp, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xc1] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = cmp, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0xd1] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = cmp, .set_operand = indirect_indexed,    .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xe0] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = cpx, .set_operand = immediate,           .flags_ = 0 },
        [0xe4] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = cpx, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xec] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = cpx, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xc0] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = cpy, .set_operand = immediate,           .flags_ = 0 },
        [0xc4] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = cpy, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xcc] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = cpy, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xc6] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = dec, .set_operand = zero_page,           .flags_ = READ_DATA | WRITE_DATA },
        [0xd6] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = dec, .set_operand = zero_page_x,         .flags_ = READ_DATA | WRITE_DATA },
        [0xce] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = dec, .set_operand = absolute,            .flags_ = READ_DATA | WRITE_DATA },
        [0xde] = { .nr_bytes_ = 3, .nr_cycles_ = 7, .execute = dec, .set_operand = absolute_x,          .flags_ = READ_DATA | WRITE_DATA },
        [0xca] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = dex, .set_operand = implied,             .flags_ = 0 },
        [0x88] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = dey, .set_operand = implied,             .flags_ = 0 },
        [0x49] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = eor, .set_operand = immediate,           .flags_ = 0 },
        [0x45] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = eor, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0x55] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = eor, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0x4d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = eor, .set_operand = absolute,            .flags_ = READ_DATA },
        [0x5d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = eor, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x59] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = eor, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x41] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = eor, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0x51] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = eor, .set_operand = indirect_indexed,    .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xe6] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = inc, .set_operand = zero_page,           .flags_ = READ_DATA | WRITE_DATA },
        [0xf6] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = inc, .set_operand = zero_page_x,         .flags_ = READ_DATA | WRITE_DATA },
        [0xee] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = inc, .set_operand = absolute,            .flags_ = READ_DATA | WRITE_DATA },
        [0xfe] = { .nr_bytes_ = 3, .nr_cycles_ = 7, .execute = inc, .set_operand = absolute_x,          .flags_ = READ_DATA | WRITE_DATA },
        [0xe8] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = inx, .set_operand = implied,             .flags_ = 0 },
        [0xc8] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = iny, .set_operand = implied,             .flags_ = 0 },
        [0x4c] = { .nr_bytes_ = 3, .nr_cycles_ = 3, .execute = jmp, .set_operand = absolute,            .flags_ = 0 },
        [0x6c] = { .nr_bytes_ = 3, .nr_cycles_ = 5, .execute = jmp, .set_operand = absolute_indirect,   .flags_ = 0 },
        [0x20] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = jsr, .set_operand = absolute,            .flags_ = 0 },
        [0xa9] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = lda, .set_operand = immediate,           .flags_ = 0 },
        [0xa5] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = lda, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xb5] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = lda, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0xad] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = lda, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xbd] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = lda, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xb9] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = lda, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xa1] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = lda, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0xb1] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = lda, .set_operand = indirect_indexed,    .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xa2] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = ldx, .set_operand = immediate,           .flags_ = 0 },
        [0xa6] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = ldx, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xb6] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = ldx, .set_operand = zero_page_y,         .flags_ = READ_DATA },
        [0xae] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ldx, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xbe] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ldx, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0xa0] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = ldy, .set_operand = immediate,           .flags_ = 0 },
        [0xa4] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = ldy, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xb4] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = ldy, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0xac] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ldy, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xbc] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ldy, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x4a] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = lsr, .set_operand = accumulator,         .flags_ = 0 },
        [0x46] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = lsr, .set_operand = zero_page,           .flags_ = READ_DATA | WRITE_DATA },
        [0x56] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = lsr, .set_operand = zero_page_x,         .flags_ = READ_DATA | WRITE_DATA },
        [0x4e] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = lsr, .set_operand = absolute,            .flags_ = READ_DATA | WRITE_DATA },
        [0x5e] = { .nr_bytes_ = 3, .nr_cycles_ = 7, .execute = lsr, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA | WRITE_DATA },
        [0xea] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,             .flags_ = 0 },
        [0x09] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = ora, .set_operand = immediate,           .flags_ = READ_DATA },
        [0x05] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = ora, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0x15] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = ora, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0x0d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ora, .set_operand = absolute,            .flags_ = READ_DATA },
        [0x1d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ora, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x19] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = ora, .set_operand = absolute_y,          .flags_ = CHECK_PAGECROSS | READ_DATA },
        [0x01] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = ora, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0x11] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = ora, .set_operand = indirect_indexed,    .flags_ = READ_DATA }, /* CHECK PAGE CROSS ??? */
        [0x48] = { .nr_bytes_ = 1, .nr_cycles_ = 3, .execute = pha, .set_operand = implied,             .flags_ = 0 },
        [0x08] = { .nr_bytes_ = 1, .nr_cycles_ = 3, .execute = php, .set_operand = implied,             .flags_ = 0 },
        [0x68] = { .nr_bytes_ = 1, .nr_cycles_ = 4, .execute = pla, .set_operand = implied,             .flags_ = 0 },
        [0x28] = { .nr_bytes_ = 1, .nr_cycles_ = 4, .execute = plp, .set_operand = implied,             .flags_ = 0 },
        [0x2a] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = rol, .set_operand = accumulator,         .flags_ = 0 },
        [0x26] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = rol, .set_operand = zero_page,           .flags_ = READ_DATA | WRITE_DATA },
        [0x36] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = rol, .set_operand = zero_page_x,         .flags_ = READ_DATA | WRITE_DATA },
        [0x2e] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = rol, .set_operand = absolute,            .flags_ = READ_DATA | WRITE_DATA },
        [0x3e] = { .nr_bytes_ = 3, .nr_cycles_ = 7, .execute = rol, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA | WRITE_DATA },
        [0x6a] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = ror, .set_operand = accumulator,         .flags_ = 0 },
        [0x66] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = ror, .set_operand = zero_page,           .flags_ = READ_DATA | WRITE_DATA },
        [0x76] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = ror, .set_operand = zero_page_x,         .flags_ = READ_DATA | WRITE_DATA },
        [0x6e] = { .nr_bytes_ = 3, .nr_cycles_ = 6, .execute = ror, .set_operand = absolute,            .flags_ = READ_DATA | WRITE_DATA },
        [0x7e] = { .nr_bytes_ = 3, .nr_cycles_ = 7, .execute = ror, .set_operand = absolute_x,          .flags_ = CHECK_PAGECROSS | READ_DATA | WRITE_DATA },
        [0x40] = { .nr_bytes_ = 1, .nr_cycles_ = 6, .execute = rti, .set_operand = implied,             .flags_ = 0 },
        [0x60] = { .nr_bytes_ = 1, .nr_cycles_ = 6, .execute = rts, .set_operand = implied,             .flags_ = 0 },
        [0xe9] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = sbc, .set_operand = immediate,           .flags_ = 0 },
        [0xe5] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = sbc, .set_operand = zero_page,           .flags_ = READ_DATA },
        [0xf5] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = sbc, .set_operand = zero_page_x,         .flags_ = READ_DATA },
        [0xed] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = sbc, .set_operand = absolute,            .flags_ = READ_DATA },
        [0xfd] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = sbc, .set_operand = absolute_x,          .flags_ = READ_DATA | CHECK_PAGECROSS },
        [0xf9] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = sbc, .set_operand = absolute_y,          .flags_ = READ_DATA | CHECK_PAGECROSS },
        [0xe1] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = sbc, .set_operand = indexed_indirect,    .flags_ = READ_DATA },
        [0xf1] = { .nr_bytes_ = 2, .nr_cycles_ = 5, .execute = sbc, .set_operand = indirect_indexed,    .flags_ = READ_DATA | CHECK_PAGECROSS },
        [0x38] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = sec, .set_operand = implied,             .flags_ = 0 },
        [0xf8] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = sed, .set_operand = implied,             .flags_ = 0 },
        [0x78] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = sei, .set_operand = implied,             .flags_ = 0 },
        [0x85] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = sta, .set_operand = zero_page,           .flags_ = WRITE_DATA },
        [0x95] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = sta, .set_operand = zero_page_x,         .flags_ = WRITE_DATA },
        [0x8d] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = sta, .set_operand = absolute,            .flags_ = WRITE_DATA },
        [0x9d] = { .nr_bytes_ = 3, .nr_cycles_ = 5, .execute = sta, .set_operand = absolute_x,          .flags_ = WRITE_DATA },
        [0x99] = { .nr_bytes_ = 3, .nr_cycles_ = 5, .execute = sta, .set_operand = absolute_y,          .flags_ = WRITE_DATA },
        [0x81] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = sta, .set_operand = indexed_indirect,    .flags_ = WRITE_DATA },
        [0x91] = { .nr_bytes_ = 2, .nr_cycles_ = 6, .execute = sta, .set_operand = indirect_indexed,    .flags_ = WRITE_DATA },
        [0x86] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = stx, .set_operand = zero_page,           .flags_ = WRITE_DATA },
        [0x96] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = stx, .set_operand = zero_page_y,         .flags_ = WRITE_DATA },
        [0x8e] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = stx, .set_operand = absolute,            .flags_ = WRITE_DATA },
        [0x84] = { .nr_bytes_ = 2, .nr_cycles_ = 3, .execute = sty, .set_operand = zero_page,           .flags_ = WRITE_DATA },
        [0x94] = { .nr_bytes_ = 2, .nr_cycles_ = 4, .execute = sty, .set_operand = zero_page_x,         .flags_ = WRITE_DATA },
        [0x8c] = { .nr_bytes_ = 3, .nr_cycles_ = 4, .execute = sty, .set_operand = absolute,            .flags_ = WRITE_DATA },
        [0xaa] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = tax, .set_operand = implied,             .flags_ = 0 },
        [0xA8] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = tay, .set_operand = implied,             .flags_ = 0 },
        [0x98] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = tya, .set_operand = implied,             .flags_ = 0 },
        [0xBA] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = tsx, .set_operand = implied,             .flags_ = 0 },
        [0x8a] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = txa, .set_operand = implied,             .flags_ = 0 },
        [0x9a] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = txs, .set_operand = implied,             .flags_ = 0 },

        /**
         * Unofficial opcodes
         */
        [0x03] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0x07] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0x0B] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0x0F] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0x13] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0x17] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0x1B] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0x1F] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0x23] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0x27] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0x2B] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0x2F] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0x33] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0x37] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0x3B] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0x3F] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0x43] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0x47] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0x4B] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0x4F] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0x53] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0x57] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0x5B] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0x5F] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0x63] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0x67] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0x6B] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0x6F] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0x73] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0x77] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0x7B] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0x7F] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0x83] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0x87] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0x8B] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0x8F] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0x93] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0x97] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0x9B] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0x9F] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0xA3] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0xA7] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0xAB] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0xAF] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0xB3] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0xB7] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0xBB] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0xBF] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0xC3] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0xC7] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0xCB] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0xCF] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0xD3] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0xD7] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0xDB] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0xDF] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        [0xE3] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indexed_indirect,  .flags_ = 0 },
        [0xE7] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page,         .flags_ = 0 },
        [0xEB] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = immediate,         .flags_ = 0 },
        [0xEF] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute,          .flags_ = 0 },
        [0xF3] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = indirect_indexed,  .flags_ = 0 },
        [0xF7] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = zero_page_x,       .flags_ = 0 },
        [0xFB] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_y,        .flags_ = 0 },
        [0xFF] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = unofficial_opcode, .set_operand = absolute_x,        .flags_ = 0 },

        /**
         * NOPs
         */
        [0x1A] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },
        [0x3A] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },
        [0x5A] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },
        [0x7A] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },
        [0xDA] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },
        [0xFA] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },
        [0xEA] = { .nr_bytes_ = 1, .nr_cycles_ = 2, .execute = nop, .set_operand = implied,           .flags_ = 0 },

        [0x82] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = immediate,           .flags_ = 0 },
        [0xC2] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = immediate,           .flags_ = 0 },
        [0xE2] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = immediate,           .flags_ = 0 },
        [0x89] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = immediate,           .flags_ = 0 },
        [0x80] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = immediate,           .flags_ = 0 },

        [0x1C] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute_x,           .flags_ = 0 },
        [0x3C] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute_x,           .flags_ = 0 },
        [0x5C] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute_x,           .flags_ = 0 },
        [0x7C] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute_x,           .flags_ = 0 },
        [0xDC] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute_x,           .flags_ = 0 },
        [0xFC] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute_x,           .flags_ = 0 },

        [0x0C] = { .nr_bytes_ = 3, .nr_cycles_ = 2, .execute = nop, .set_operand = absolute,           .flags_ = 0 },

        [0x14] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page_x,           .flags_ = 0 },
        [0x34] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page_x,           .flags_ = 0 },
        [0x54] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page_x,           .flags_ = 0 },
        [0x74] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page_x,           .flags_ = 0 },
        [0xD4] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page_x,           .flags_ = 0 },
        [0xF4] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page_x,           .flags_ = 0 },

        [0x04] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page,           .flags_ = 0 },
        [0x44] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page,           .flags_ = 0 },
        [0x64] = { .nr_bytes_ = 2, .nr_cycles_ = 2, .execute = nop, .set_operand = zero_page,           .flags_ = 0 },
};
